### ISSUE TITLE
OVER_QUERY_LIMIT error despite seemingly correct setup

### ISSUE THREAD

**Issue by lekv** [mrdis/MMM-google-route#20]
I keep getting an "OVER_QUERY_LIMIT" error from the directions API after 12-ish hours of runtime. Refreshing the page immediately makes it go away until it shows up again hours later. I also don't see any errors on the Google console, but when the errors appear, I do see a reduced number of requests:

![Screen Shot 2019-07-03 at 11 32 37 AM](https://user-images.githubusercontent.com/151514/60616701-ee421f00-9d86-11e9-8598-f9794579165f.png)

Overall my limits there are high enough not to hit them.

How can I debug this issue? Could this be a different error/problem that gets masked as OVER_QUERY_LIMIT? The whole thing runs on a raspberry pi 3.

**Comment by mrdis** [comment]
Hi, I don't know if it's too late for this now, I must have missed the notification. :(
Do you still have this issue?

**Comment by lekv** [comment]
I haven't checked in a while since I hit the end of the free tier of the Google APIs and haven't gotten around to re-enabling it with longer intervals. I'll report back if I see this again, but until then I'm good with closing it.

**Comment by Maxxell** [comment]
Hiya!
I got this similar error on my new mirror.  I disabled this module for now, but while poking around the google cloud platform pages, I found this: "If you are seeing "Can't load" or Rate Limit Exceeded errors in your mobile app, your app may be using a deprecated version of the Places SDK for Android or iOS. Find migration guides for Android and iOS to begin using the new Places SDKs."

Is it possible this is the root cause?  Anything else I can do to help diagnose?
