### ISSUE TITLE
Fit route to bounds?

### ISSUE THREAD

**Issue by eddiewastaken** [mrdis/MMM-google-route#27]
Lots of wasted space around the route shown on the map. Any way to fit the route to the bounds of the map? Seems it's supported by the API.

**Comment by mrdis** [comment]
The current implementation automatically display the map at the maximum zoom level that allows viewing the whole route.
The problem is that google maps only support discrete zoom levels, so the route that you are displaying would not fit using a higher zoom level.
This leads to some empty space around the route.
If you think this is not the case and there is another type of issue, please tell me how to reproduce it.
